package com.test.farmers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Farmer service. Represents a row in the &quot;lr_Farmer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.farmers.model.impl.FarmerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.farmers.model.impl.FarmerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Farmer
 * @see com.test.farmers.model.impl.FarmerImpl
 * @see com.test.farmers.model.impl.FarmerModelImpl
 * @generated
 */
public interface FarmerModel extends BaseModel<Farmer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a farmer model instance should use the {@link Farmer} interface instead.
     */

    /**
     * Returns the primary key of this farmer.
     *
     * @return the primary key of this farmer
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this farmer.
     *
     * @param primaryKey the primary key of this farmer
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the farmer ID of this farmer.
     *
     * @return the farmer ID of this farmer
     */
    public long getFarmerId();

    /**
     * Sets the farmer ID of this farmer.
     *
     * @param farmerId the farmer ID of this farmer
     */
    public void setFarmerId(long farmerId);

    /**
     * Returns the name of this farmer.
     *
     * @return the name of this farmer
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this farmer.
     *
     * @param name the name of this farmer
     */
    public void setName(String name);

    /**
     * Returns the legal form of this farmer.
     *
     * @return the legal form of this farmer
     */
    @AutoEscape
    public String getLegalForm();

    /**
     * Sets the legal form of this farmer.
     *
     * @param legalForm the legal form of this farmer
     */
    public void setLegalForm(String legalForm);

    /**
     * Returns the inn of this farmer.
     *
     * @return the inn of this farmer
     */
    public long getInn();

    /**
     * Sets the inn of this farmer.
     *
     * @param inn the inn of this farmer
     */
    public void setInn(long inn);

    /**
     * Returns the kpp of this farmer.
     *
     * @return the kpp of this farmer
     */
    public int getKpp();

    /**
     * Sets the kpp of this farmer.
     *
     * @param kpp the kpp of this farmer
     */
    public void setKpp(int kpp);

    /**
     * Returns the ogrn of this farmer.
     *
     * @return the ogrn of this farmer
     */
    public long getOgrn();

    /**
     * Sets the ogrn of this farmer.
     *
     * @param ogrn the ogrn of this farmer
     */
    public void setOgrn(long ogrn);

    /**
     * Returns the district ID of this farmer.
     *
     * @return the district ID of this farmer
     */
    public long getDistrictId();

    /**
     * Sets the district ID of this farmer.
     *
     * @param districtId the district ID of this farmer
     */
    public void setDistrictId(long districtId);

    /**
     * Returns the registration date of this farmer.
     *
     * @return the registration date of this farmer
     */
    public Date getRegistrationDate();

    /**
     * Sets the registration date of this farmer.
     *
     * @param registrationDate the registration date of this farmer
     */
    public void setRegistrationDate(Date registrationDate);

    /**
     * Returns the is archive of this farmer.
     *
     * @return the is archive of this farmer
     */
    public boolean getIsArchive();

    /**
     * Returns <code>true</code> if this farmer is is archive.
     *
     * @return <code>true</code> if this farmer is is archive; <code>false</code> otherwise
     */
    public boolean isIsArchive();

    /**
     * Sets whether this farmer is is archive.
     *
     * @param isArchive the is archive of this farmer
     */
    public void setIsArchive(boolean isArchive);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.test.farmers.model.Farmer farmer);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.test.farmers.model.Farmer> toCacheModel();

    @Override
    public com.test.farmers.model.Farmer toEscapedModel();

    @Override
    public com.test.farmers.model.Farmer toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
