package com.test.farmers.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.test.farmers.model.Farmer;
import com.test.farmers.model.FarmerModel;
import com.test.farmers.model.FarmerSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Farmer service. Represents a row in the &quot;lr_Farmer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.test.farmers.model.FarmerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FarmerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FarmerImpl
 * @see com.test.farmers.model.Farmer
 * @see com.test.farmers.model.FarmerModel
 * @generated
 */
@JSON(strict = true)
public class FarmerModelImpl extends BaseModelImpl<Farmer>
    implements FarmerModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a farmer model instance should use the {@link com.test.farmers.model.Farmer} interface instead.
     */
    public static final String TABLE_NAME = "lr_Farmer";
    public static final Object[][] TABLE_COLUMNS = {
            { "farmerId", Types.BIGINT },
            { "name", Types.VARCHAR },
            { "legalForm", Types.VARCHAR },
            { "inn", Types.BIGINT },
            { "kpp", Types.INTEGER },
            { "ogrn", Types.BIGINT },
            { "districtId", Types.BIGINT },
            { "registrationDate", Types.TIMESTAMP },
            { "isArchive", Types.BOOLEAN }
        };
    public static final String TABLE_SQL_CREATE = "create table lr_Farmer (farmerId LONG not null primary key,name VARCHAR(75) null,legalForm VARCHAR(75) null,inn LONG,kpp INTEGER,ogrn LONG,districtId LONG,registrationDate DATE null,isArchive BOOLEAN)";
    public static final String TABLE_SQL_DROP = "drop table lr_Farmer";
    public static final String ORDER_BY_JPQL = " ORDER BY farmer.name ASC";
    public static final String ORDER_BY_SQL = " ORDER BY lr_Farmer.name ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.test.farmers.model.Farmer"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.test.farmers.model.Farmer"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.test.farmers.model.Farmer"),
            true);
    public static long INN_COLUMN_BITMASK = 1L;
    public static long ISARCHIVE_COLUMN_BITMASK = 2L;
    public static long NAME_COLUMN_BITMASK = 4L;
    public static long REGISTRATIONDATE_COLUMN_BITMASK = 8L;
    public static final String MAPPING_TABLE_LR_FARMERS_DISTRICTS_NAME = "lr_Farmers_Districts";
    public static final Object[][] MAPPING_TABLE_LR_FARMERS_DISTRICTS_COLUMNS = {
            { "districtId", Types.BIGINT },
            { "farmerId", Types.BIGINT }
        };
    public static final String MAPPING_TABLE_LR_FARMERS_DISTRICTS_SQL_CREATE = "create table lr_Farmers_Districts (districtId LONG not null,farmerId LONG not null,primary key (districtId, farmerId))";
    public static final boolean FINDER_CACHE_ENABLED_LR_FARMERS_DISTRICTS = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.lr_Farmers_Districts"), true);
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.test.farmers.model.Farmer"));
    private static ClassLoader _classLoader = Farmer.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Farmer.class };
    private long _farmerId;
    private String _name;
    private String _originalName;
    private String _legalForm;
    private long _inn;
    private long _originalInn;
    private boolean _setOriginalInn;
    private int _kpp;
    private long _ogrn;
    private long _districtId;
    private Date _registrationDate;
    private Date _originalRegistrationDate;
    private boolean _isArchive;
    private boolean _originalIsArchive;
    private boolean _setOriginalIsArchive;
    private long _columnBitmask;
    private Farmer _escapedModel;

    public FarmerModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Farmer toModel(FarmerSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Farmer model = new FarmerImpl();

        model.setFarmerId(soapModel.getFarmerId());
        model.setName(soapModel.getName());
        model.setLegalForm(soapModel.getLegalForm());
        model.setInn(soapModel.getInn());
        model.setKpp(soapModel.getKpp());
        model.setOgrn(soapModel.getOgrn());
        model.setDistrictId(soapModel.getDistrictId());
        model.setRegistrationDate(soapModel.getRegistrationDate());
        model.setIsArchive(soapModel.getIsArchive());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Farmer> toModels(FarmerSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Farmer> models = new ArrayList<Farmer>(soapModels.length);

        for (FarmerSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _farmerId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setFarmerId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _farmerId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Farmer.class;
    }

    @Override
    public String getModelClassName() {
        return Farmer.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("farmerId", getFarmerId());
        attributes.put("name", getName());
        attributes.put("legalForm", getLegalForm());
        attributes.put("inn", getInn());
        attributes.put("kpp", getKpp());
        attributes.put("ogrn", getOgrn());
        attributes.put("districtId", getDistrictId());
        attributes.put("registrationDate", getRegistrationDate());
        attributes.put("isArchive", getIsArchive());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long farmerId = (Long) attributes.get("farmerId");

        if (farmerId != null) {
            setFarmerId(farmerId);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String legalForm = (String) attributes.get("legalForm");

        if (legalForm != null) {
            setLegalForm(legalForm);
        }

        Long inn = (Long) attributes.get("inn");

        if (inn != null) {
            setInn(inn);
        }

        Integer kpp = (Integer) attributes.get("kpp");

        if (kpp != null) {
            setKpp(kpp);
        }

        Long ogrn = (Long) attributes.get("ogrn");

        if (ogrn != null) {
            setOgrn(ogrn);
        }

        Long districtId = (Long) attributes.get("districtId");

        if (districtId != null) {
            setDistrictId(districtId);
        }

        Date registrationDate = (Date) attributes.get("registrationDate");

        if (registrationDate != null) {
            setRegistrationDate(registrationDate);
        }

        Boolean isArchive = (Boolean) attributes.get("isArchive");

        if (isArchive != null) {
            setIsArchive(isArchive);
        }
    }

    @JSON
    @Override
    public long getFarmerId() {
        return _farmerId;
    }

    @Override
    public void setFarmerId(long farmerId) {
        _farmerId = farmerId;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _columnBitmask = -1L;

        if (_originalName == null) {
            _originalName = _name;
        }

        _name = name;
    }

    public String getOriginalName() {
        return GetterUtil.getString(_originalName);
    }

    @JSON
    @Override
    public String getLegalForm() {
        if (_legalForm == null) {
            return StringPool.BLANK;
        } else {
            return _legalForm;
        }
    }

    @Override
    public void setLegalForm(String legalForm) {
        _legalForm = legalForm;
    }

    @JSON
    @Override
    public long getInn() {
        return _inn;
    }

    @Override
    public void setInn(long inn) {
        _columnBitmask |= INN_COLUMN_BITMASK;

        if (!_setOriginalInn) {
            _setOriginalInn = true;

            _originalInn = _inn;
        }

        _inn = inn;
    }

    public long getOriginalInn() {
        return _originalInn;
    }

    @JSON
    @Override
    public int getKpp() {
        return _kpp;
    }

    @Override
    public void setKpp(int kpp) {
        _kpp = kpp;
    }

    @JSON
    @Override
    public long getOgrn() {
        return _ogrn;
    }

    @Override
    public void setOgrn(long ogrn) {
        _ogrn = ogrn;
    }

    @JSON
    @Override
    public long getDistrictId() {
        return _districtId;
    }

    @Override
    public void setDistrictId(long districtId) {
        _districtId = districtId;
    }

    @JSON
    @Override
    public Date getRegistrationDate() {
        return _registrationDate;
    }

    @Override
    public void setRegistrationDate(Date registrationDate) {
        _columnBitmask |= REGISTRATIONDATE_COLUMN_BITMASK;

        if (_originalRegistrationDate == null) {
            _originalRegistrationDate = _registrationDate;
        }

        _registrationDate = registrationDate;
    }

    public Date getOriginalRegistrationDate() {
        return _originalRegistrationDate;
    }

    @JSON
    @Override
    public boolean getIsArchive() {
        return _isArchive;
    }

    @Override
    public boolean isIsArchive() {
        return _isArchive;
    }

    @Override
    public void setIsArchive(boolean isArchive) {
        _columnBitmask |= ISARCHIVE_COLUMN_BITMASK;

        if (!_setOriginalIsArchive) {
            _setOriginalIsArchive = true;

            _originalIsArchive = _isArchive;
        }

        _isArchive = isArchive;
    }

    public boolean getOriginalIsArchive() {
        return _originalIsArchive;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Farmer.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Farmer toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Farmer) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        FarmerImpl farmerImpl = new FarmerImpl();

        farmerImpl.setFarmerId(getFarmerId());
        farmerImpl.setName(getName());
        farmerImpl.setLegalForm(getLegalForm());
        farmerImpl.setInn(getInn());
        farmerImpl.setKpp(getKpp());
        farmerImpl.setOgrn(getOgrn());
        farmerImpl.setDistrictId(getDistrictId());
        farmerImpl.setRegistrationDate(getRegistrationDate());
        farmerImpl.setIsArchive(getIsArchive());

        farmerImpl.resetOriginalValues();

        return farmerImpl;
    }

    @Override
    public int compareTo(Farmer farmer) {
        int value = 0;

        value = getName().compareTo(farmer.getName());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Farmer)) {
            return false;
        }

        Farmer farmer = (Farmer) obj;

        long primaryKey = farmer.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        FarmerModelImpl farmerModelImpl = this;

        farmerModelImpl._originalName = farmerModelImpl._name;

        farmerModelImpl._originalInn = farmerModelImpl._inn;

        farmerModelImpl._setOriginalInn = false;

        farmerModelImpl._originalRegistrationDate = farmerModelImpl._registrationDate;

        farmerModelImpl._originalIsArchive = farmerModelImpl._isArchive;

        farmerModelImpl._setOriginalIsArchive = false;

        farmerModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Farmer> toCacheModel() {
        FarmerCacheModel farmerCacheModel = new FarmerCacheModel();

        farmerCacheModel.farmerId = getFarmerId();

        farmerCacheModel.name = getName();

        String name = farmerCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            farmerCacheModel.name = null;
        }

        farmerCacheModel.legalForm = getLegalForm();

        String legalForm = farmerCacheModel.legalForm;

        if ((legalForm != null) && (legalForm.length() == 0)) {
            farmerCacheModel.legalForm = null;
        }

        farmerCacheModel.inn = getInn();

        farmerCacheModel.kpp = getKpp();

        farmerCacheModel.ogrn = getOgrn();

        farmerCacheModel.districtId = getDistrictId();

        Date registrationDate = getRegistrationDate();

        if (registrationDate != null) {
            farmerCacheModel.registrationDate = registrationDate.getTime();
        } else {
            farmerCacheModel.registrationDate = Long.MIN_VALUE;
        }

        farmerCacheModel.isArchive = getIsArchive();

        return farmerCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(19);

        sb.append("{farmerId=");
        sb.append(getFarmerId());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", legalForm=");
        sb.append(getLegalForm());
        sb.append(", inn=");
        sb.append(getInn());
        sb.append(", kpp=");
        sb.append(getKpp());
        sb.append(", ogrn=");
        sb.append(getOgrn());
        sb.append(", districtId=");
        sb.append(getDistrictId());
        sb.append(", registrationDate=");
        sb.append(getRegistrationDate());
        sb.append(", isArchive=");
        sb.append(getIsArchive());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(31);

        sb.append("<model><model-name>");
        sb.append("com.test.farmers.model.Farmer");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>farmerId</column-name><column-value><![CDATA[");
        sb.append(getFarmerId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>legalForm</column-name><column-value><![CDATA[");
        sb.append(getLegalForm());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>inn</column-name><column-value><![CDATA[");
        sb.append(getInn());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>kpp</column-name><column-value><![CDATA[");
        sb.append(getKpp());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ogrn</column-name><column-value><![CDATA[");
        sb.append(getOgrn());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>districtId</column-name><column-value><![CDATA[");
        sb.append(getDistrictId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>registrationDate</column-name><column-value><![CDATA[");
        sb.append(getRegistrationDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>isArchive</column-name><column-value><![CDATA[");
        sb.append(getIsArchive());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
